/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecoflow.view;

import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.outros.Tela;

/**
 *
 * @author vinicius
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dpTelaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        imCadastrarCentral = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miBuscarLeitura = new javax.swing.JMenuItem();
        miEditarLeitura = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        imConexao = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        imSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ecoflow Studio");
        setExtendedState(MAXIMIZED_BOTH);
        setIconImage(Toolkit.getDefaultToolkit().getImage("./imagem/ECOFlow.png"));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jScrollPane1.setBorder(null);

        dpTelaPrincipal.setPreferredSize(new java.awt.Dimension(600, 300));

        javax.swing.GroupLayout dpTelaPrincipalLayout = new javax.swing.GroupLayout(dpTelaPrincipal);
        dpTelaPrincipal.setLayout(dpTelaPrincipalLayout);
        dpTelaPrincipalLayout.setHorizontalGroup(
            dpTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        dpTelaPrincipalLayout.setVerticalGroup(
            dpTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(dpTelaPrincipal);

        jMenu1.setMnemonic('a');
        jMenu1.setText("Arquivo");

        imCadastrarCentral.setText("Cadastrar Central");
        imCadastrarCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imCadastrarCentralActionPerformed(evt);
            }
        });
        jMenu1.add(imCadastrarCentral);

        jMenuBar1.add(jMenu1);

        jMenu4.setMnemonic('m');
        jMenu4.setText("Em Campo");

        miBuscarLeitura.setText("Buscar Leituras");
        miBuscarLeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBuscarLeituraActionPerformed(evt);
            }
        });
        jMenu4.add(miBuscarLeitura);

        miEditarLeitura.setText("Editar Leituras");
        miEditarLeitura.setEnabled(false);
        miEditarLeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarLeituraActionPerformed(evt);
            }
        });
        jMenu4.add(miEditarLeitura);

        jMenuBar1.add(jMenu4);

        jMenu2.setMnemonic('d');
        jMenu2.setText("Editar");

        imConexao.setText("Conexão");
        imConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imConexaoActionPerformed(evt);
            }
        });
        jMenu2.add(imConexao);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('j');
        jMenu3.setText("Ajuda");

        imSobre.setText("Sobre");
        imSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imSobreActionPerformed(evt);
            }
        });
        jMenu3.add(imSobre);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imSobreActionPerformed
        Sobre sobre = new Sobre();
        Tela.chamarInternalFrame(dpTelaPrincipal,sobre, false);
    }//GEN-LAST:event_imSobreActionPerformed

    private void imConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imConexaoActionPerformed
        // TODO add your handling code here:
        EditarConexao editarConexao = new EditarConexao();
        Tela.chamarInternalFrame(dpTelaPrincipal, editarConexao, false);
    }//GEN-LAST:event_imConexaoActionPerformed

    private void miBuscarLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBuscarLeituraActionPerformed
        TelaLeitura telaUnidade;
        try {
            telaUnidade = new TelaLeitura();
            Tela.chamarInternalFrame(dpTelaPrincipal, telaUnidade, true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Problema na conexão!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miBuscarLeituraActionPerformed

    private void imCadastrarCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imCadastrarCentralActionPerformed
        TelaCadastroCentral telaCentral;
        try {
            telaCentral = new TelaCadastroCentral(dpTelaPrincipal);
            Tela.chamarInternalFrame(dpTelaPrincipal,telaCentral, true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Problema na conexão!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_imCadastrarCentralActionPerformed

    private void miEditarLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditarLeituraActionPerformed
        // TODO add your handling code here:
        TelaEditarLeitura telaEditarLeitura;
        try {
            telaEditarLeitura = new TelaEditarLeitura();
            Tela.chamarInternalFrame(dpTelaPrincipal, telaEditarLeitura, true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Problema na conexão!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miEditarLeituraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpTelaPrincipal;
    private javax.swing.JMenuItem imCadastrarCentral;
    private javax.swing.JMenuItem imConexao;
    private javax.swing.JMenuItem imSobre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miBuscarLeitura;
    private javax.swing.JMenuItem miEditarLeitura;
    // End of variables declaration//GEN-END:variables
}
